version: '3.8'

networks:
  polybank:
    driver: bridge
    name: polybank

services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    container_name: rabbitmq_polybank
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - polybank
  postgres:
    container_name: postgres_polybank
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - polybank
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=password
    ports:
      - '6379:6379'
    volumes:
      - redis_volume:/var/lib/redis/data
    networks:
      - polybank



volumes:
  postgres_volume:
  redis_volume:
